### ISSUE TITLE
[BUG]  Torrents of 2 MiB in size cannot be uploaded.

### ISSUE THREAD

**Issue by ripsnortntear** [XxAcielxX/docker-rutorrent#11]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/XxAcielxX/docker-rutorrent/blob/main/.github/SUPPORT.md)

### Is there an existing opened or closed issue for this?

- [X] I have searched all the existing opened or closed issues

### Current Behavior

rtorrent is not allowing torrent files over 2 MiB

### Expected Behavior

should be able to upload torrent of any size. Current one is 16.5 MiB

### Steps To Reproduce

try to upload a torrent on a new dockerfile pull with no previous docker usage on server.

### Image & Browser details

```markdown
Image: v4.0-a01
Browser: Edge (Desktop)
Tried different browser? yes same error
```

### Environment

```markdown
- OS: Ubuntu 22.04
- Docker version: Client: Docker Engine - Community Version: 23.0.1
- How docker service was installed: sudo apt install docker-ce
```

### CPU architecture

x86-64

### Container creation

```bash
docker compose up -d
```

### Container logs

```bash
f
```

### Additional info

![Screenshot 2023-03-23 012354](https://user-images.githubusercontent.com/96964368/227112255-d7658fca-2a7e-438f-a63d-cbd20c42dc89.png)

**Comment by XxAcielxX** [comment]
Hi @ripsnortntear,

Can you kindly post the sample torrent file large then 2MB. I'm suspecting that this limit is set in the base image (Crazy-Max).

**Comment by XxAcielxX** [comment]
You have closed the issue, but did you find a fix for this? It might help others as well.

**Comment by ripsnortntear** [comment]
when i tried to adjust the file plugin.. it wiped all my data. i just gave up and went with the watch folder.. this allowed me to upload a 16mb torrent.
