### ISSUE TITLE
Right Click > Remove is removing data

### ISSUE THREAD

**Issue by cfw34683** [XxAcielxX/docker-rutorrent#2]
Ratio Groups, Right Clicking, anything set to remove torrent removes data as well. this only started a few days ago. it used to remove just the torrent leaving the data. now remove and delete data and remove do the same thing
![Screenshot 2021-12-04 111330](https://user-images.githubusercontent.com/44150081/144716561-c2791bf5-47da-4015-aa6d-0dc10d629132.png)
.

**Comment by XxAcielxX** [comment]
Hello @cfw34683,

I think this issue is coming from upstream image, try this fix and report back please.

Edit & uncomment line 59 in file `/data/rtorrent/.rtorrent.rc`

```
# Erase data when torrent deleted (no need erasedata plugin on ruTorrent)
method.set_key = event.download.erased,delete_erased,"execute=rm,-rf,--,$d.data_path="
```

Restart the container and test.

**Comment by cfw34683** [comment]
this workaround has returned the two commands to their former status.
