### ISSUE TITLE
Pterodactyl Support

### ISSUE THREAD

**Issue by ghost** [XxAcielxX/docker-rutorrent#3]
We are trying to get this image into the Pterodactyl panel and are having an issue. The panel requires a startup command to be run on the container to start it. We looked at the dockerfile to no avail. Is there a command thats run?

**Comment by XxAcielxX** [comment]
Hi @cfw34683
I haven't used Pterodactyl Panel ever and if I'm getting you correct, I think you should look here from upstream:
[04-create-services.sh](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/rootfs/etc/cont-init.d/04-create-services.sh)

Run command is located in `/etc/services.d/rtorrent/run` inside the container.
