### ISSUE TITLE
JS Errors

### ISSUE THREAD

**Issue by ripsnortntear** [XxAcielxX/docker-rutorrent#7]
Just did `docker compose stop` `docker system prune -f -a` then reloaded rtorrent with `docker compose up -d` and get this in the logs when start up

[14.01.2023 05:05:18] WebUI started.
[14.01.2023 05:05:24] JS error: [http://192.168.1.115:8081/plugins/filedrop//jquery.filedrop.js : 28] TypeError: jQuery.event.props is undefined
[14.01.2023 05:05:24] JS error: [http://192.168.1.115:8081/ line 2 > injectedScript : 2584] TypeError: $(...).filedrop is not a function

not sure if it will effect how it works.. we shall see

**Comment by ripsnortntear** [comment]
![Screenshot 2023-01-14 052117](https://user-images.githubusercontent.com/96964368/212467283-05121340-4859-4810-ba92-87bcf7051333.jpg)

**Comment by ripsnortntear** [comment]
this might help in locating the issue? i think i found the `undefined` this use to say something else

**Comment by XxAcielxX** [comment]
Hi there,

Just want to make sure, have you read and applied this #5?

**Comment by ripsnortntear** [comment]
Yes. Sent from my iPhoneOn Jan 14, 2023, at 5:32 AM, Aciel ***@***.***> wrote:﻿
Hi there,
Just want to make sure, have you read and applied this #5?

**Comment by XxAcielxX** [comment]
Can you tell me about your setup? Which `arch` are you on, `docker create/run cli` or `docker-compose`. And also kindly post your `.rtorrent.rc`

**Comment by ripsnortntear** [comment]
`# Maximum and minimum number of peers to connect to per torrent
throttle.min_peers.normal.set = 1
throttle.max_peers.normal.set = 100

# Same as above but for seeding completed torrents (-1 = same as downloading)
throttle.min_peers.seed.set = 1
throttle.max_peers.seed.set = 50

# Maximum number of simultanious uploads per torrent
throttle.max_uploads.set = 15

# Global upload and download rate in KiB. "0" for unlimited
throttle.global_down.max_rate.set_kb = 0
throttle.global_up.max_rate.set_kb = 0

# Enable DHT support for trackerless torrents or when all trackers are down
# May be set to "disable" (completely disable DHT), "off" (do not start DHT),
# "auto" (start and stop DHT as needed), or "on" (start DHT immediately)
dht.mode.set = auto

# Enable peer exchange (for torrents not marked private)
protocol.pex.set = no

# Check hash for finished torrents. Might be usefull until the bug is
# fixed that causes lack of diskspace not to be properly reported
pieces.hash.on_completion.set = no

# Set whether the client should try to connect to UDP trackers
#trackers.use_udp.set = yes

# Set the max amount of memory address space used to mapping file chunks. This refers to memory mapping, not
# physical memory allocation. Default: 1GB (max_memory_usage)
# This may also be set using ulimit -m where 3/4 will be allocated to file chunks
#pieces.memory.max.set = 1GB

# Alternative calls to bind and ip that should handle dynamic ip's
#schedule2 = ip_tick,0,1800,ip=rakshasa
#schedule2 = bind_tick,0,1800,bind=rakshasa

# Encryption options, set to none (default) or any combination of the following:
# allow_incoming, try_outgoing, require, require_RC4, enable_retry, prefer_plaintext
protocol.encryption.set = allow_incoming,try_outgoing,enable_retry

# Set the umask for this process, which is applied to all files created by the program
#system.umask.set = 0022

# Add a preferred filename encoding to the list
encoding.add = UTF-8

# Default download directory for torrents
directory.default.set = (cat,(cfg.download))

# Watch a directory for new torrents, and stop those that have been deleted
schedule2 = watch_directory, 1, 1, (cat,"load.start=",(cfg.watch),"*.torrent")
schedule2 = untied_directory, 5, 5, (cat,"stop_untied=",(cfg.watch),"*.torrent")

# Close torrents when diskspace is low
schedule2 = monitor_diskspace, 15, 60, ((close_low_diskspace,1000M))

# Move finished (no need Autotools/Automove plugin on ruTorrent)
#method.insert = d.get_finished_dir, simple, "cat=$cfg.download_complete=,$d.custom1="
#method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="
#method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.data_path=,$d.get_finished_dir="

# Erase data when torrent deleted (no need erasedata plugin on ruTorrent)
# method.set_key = event.download.erased,delete_erased,"execute=rm,-rf,--,$d.data_path="
`

**Comment by ripsnortntear** [comment]
github claims file is hidden.. i unhid it.. its not hidden,.., iull have to post it in long fomat.. im sry\

**Comment by ripsnortntear** [comment]
# Maximum and minimum number of peers to connect to per torrent
throttle.min_peers.normal.set = 1
throttle.max_peers.normal.set = 100

# Same as above but for seeding completed torrents (-1 = same as downloading)
throttle.min_peers.seed.set = 1
throttle.max_peers.seed.set = 50

# Maximum number of simultanious uploads per torrent
throttle.max_uploads.set = 15

# Global upload and download rate in KiB. "0" for unlimited
throttle.global_down.max_rate.set_kb = 0
throttle.global_up.max_rate.set_kb = 0

# Enable DHT support for trackerless torrents or when all trackers are down
# May be set to "disable" (completely disable DHT), "off" (do not start DHT),
# "auto" (start and stop DHT as needed), or "on" (start DHT immediately)
dht.mode.set = auto

# Enable peer exchange (for torrents not marked private)
protocol.pex.set = no

# Check hash for finished torrents. Might be usefull until the bug is
# fixed that causes lack of diskspace not to be properly reported
pieces.hash.on_completion.set = no

# Set whether the client should try to connect to UDP trackers
#trackers.use_udp.set = yes

# Set the max amount of memory address space used to mapping file chunks. This refers to memory mapping, not
# physical memory allocation. Default: 1GB (max_memory_usage)
# This may also be set using ulimit -m where 3/4 will be allocated to file chunks
#pieces.memory.max.set = 1GB

# Alternative calls to bind and ip that should handle dynamic ip's
#schedule2 = ip_tick,0,1800,ip=rakshasa
#schedule2 = bind_tick,0,1800,bind=rakshasa

# Encryption options, set to none (default) or any combination of the following:
# allow_incoming, try_outgoing, require, require_RC4, enable_retry, prefer_plaintext
protocol.encryption.set = allow_incoming,try_outgoing,enable_retry

# Set the umask for this process, which is applied to all files created by the program
#system.umask.set = 0022

# Add a preferred filename encoding to the list
encoding.add = UTF-8

# Default download directory for torrents
directory.default.set = (cat,(cfg.download))

# Watch a directory for new torrents, and stop those that have been deleted
schedule2 = watch_directory, 1, 1, (cat,"load.start=",(cfg.watch),"*.torrent")
schedule2 = untied_directory, 5, 5, (cat,"stop_untied=",(cfg.watch),"*.torrent")

# Close torrents when diskspace is low
schedule2 = monitor_diskspace, 15, 60, ((close_low_diskspace,1000M))

# Move finished (no need Autotools/Automove plugin on ruTorrent)
#method.insert = d.get_finished_dir, simple, "cat=$cfg.download_complete=,$d.custom1="
#method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="
#method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.data_path=,$d.get_finished_dir="

# Erase data when torrent deleted (no need erasedata plugin on ruTorrent)
# method.set_key = event.download.erased,delete_erased,"execute=rm,-rf,--,$d.data_path="

**Comment by XxAcielxX** [comment]
I ran a test container to check this error myself, but everything seems to be working on my side. I did both fresh data & old update from image v3.10-a09.

Can you kindly create a separate test container with a different volume for `/data ` & ports and report back.

Note: If you have a long logs/text, please use [Pastebin](https://pastebin.com), [dPaste](https://dpaste.com) or [0bin](https://0bin.net) and share the link.

**Comment by ripsnortntear** [comment]
In this video I start out showing the current container and data folder (new pull data) and the state of the rtorrent. This ends in being solved by putting the data folder in a new folder called `isitnice` and a new port. Why this worked idk. But heres a vid

https://user-images.githubusercontent.com/96964368/212533177-9f232688-e960-4a93-9d83-abe8aca19496.mp4

**Comment by ripsnortntear** [comment]
So im going to leave it as it is and not try and figure out why its working in this new config. It even persists thru reboots.       Thanks for the help!

**Comment by XxAcielxX** [comment]
Maybe some unknown factor could have caused it, some bad cache or corrupted file. I was going to suggest you the same that to create a new container and then copy over your user files and `session` directory.  I'm glad it worked in the end.

Have a good day, Regards
